### ISSUE TITLE
ISS-181: during postgres execution failure with negative bitmapset member

### ISSUE THREAD

**Issue by stormalf** [stormalf/chibicc#84]
during postgres execution failure with negative bitmapset member : 

performing post-bootstrap initialization ... 2024-10-26 11:52:38.760 CEST [415899] FATAL:  negative bitmapset member not allowed
2024-10-26 11:52:38.760 CEST [415899] STATEMENT:
        WITH funcdescs AS ( SELECT p.oid as p_oid, o.oid as o_oid, oprname FROM pg_proc p JOIN pg_operator o ON oprcode = p.oid ) INSERT INTO pg_description   SELECT p_oid, 'pg_proc'::regclass, 0,     'implementation of ' || oprname || ' operator'   FROM funcdescs   WHERE NOT EXISTS (SELECT 1 FROM pg_description    WHERE objoid = p_oid AND classoid = 'pg_proc'::regclass)   AND NOT EXISTS (SELECT 1 FROM pg_description    WHERE objoid = o_oid AND classoid = 'pg_operator'::regclass         AND description LIKE 'deprecated%');

child process exited with exit code 1

**Comment by stormalf** [comment]
backtrace : 
0x0000000000ea7b22 in bms_add_member () at bitmapset.c:823
823                             int x = 0;
(gdb) bt
#0  0x0000000000ea7b22 in bms_add_member () at bitmapset.c:823
#1  0x000000000107315d in remove_self_joins_recurse () at analyzejoins.c:2365
#2  0x000000000107c7d1 in remove_useless_self_joins () at analyzejoins.c:2466
#3  0x00000000010af7ef in query_planner () at planmain.c:236
#4  0x00000000010c9946 in grouping_planner () at planner.c:1510
#5  0x00000000010cfe32 in subquery_planner () at planner.c:1079
#6  0x00000000010d051f in standard_planner () at planner.c:408
#7  0x00000000010d34e5 in planner () at planner.c:276
#8  0x0000000001462f97 in pg_plan_query () at postgres.c:903
#9  0x0000000001462e37 in pg_plan_queries () at postgres.c:995
#10 0x00000000014581e2 in exec_simple_query () at postgres.c:1192
#11 0x000000000145edb0 in PostgresMain () at postgres.c:4675
#12 0x00000000014603d6 in PostgresSingleUserMain () at postgres.c:4128
#13 0x0000000000ea4f8b in main () at main.c:194
