### ISSUE TITLE
ISS-182: during postgres compile, the execution failed with pfree called with invalid pointer

### ISSUE THREAD

**Issue by stormalf** [stormalf/chibicc#86]
during postgres compile, the execution failed with pfree called with invalid pointer
performing post-bootstrap initialization ... 2024-10-28 07:40:58.746 CET [121131] FATAL:  pfree called with invalid pointer 0x49f77e8 (header 0x0000000003b80280)
2024-10-28 07:40:58.746 CET [121131] CONTEXT:  while scanning block 34 of relation "pg_catalog.pg_proc"
2024-10-28 07:40:58.746 CET [121131] STATEMENT:  VACUUM FREEZE;

**Comment by stormalf** [comment]
here the backtrace : 
#0  0x0000000001b45161 in BogusFree () at mcxt.c:289
#1  0x0000000001b471d7 in pfree () at mcxt.c:182
#2  0x000000000050beab in local_ts_free_leaf () at ../../../../src/include/lib/radixtree.h:970
#3  0x000000000050d09f in local_ts_set () at tidstore.c:1
#4  0x0000000000516a05 in TidStoreSetBlockOffsets () at tidstore.c:424
#5  0x0000000000620f66 in dead_items_add () at vacuumlazy.c:2897
#6  0x0000000000625bed in lazy_scan_prune () at vacuumlazy.c:1500
#7  0x0000000000627a0f in lazy_scan_heap () at vacuumlazy.c:975
#8  0x000000000062954a in heap_vacuum_rel () at vacuumlazy.c:497
#9  0x0000000000d1a681 in table_relation_vacuum () at ../../../src/include/access/tableam.h:1710
#10 0x0000000000d0f8cf in vacuum_rel () at vacuum.c:2210
#11 0x0000000000d16d4f in vacuum () at vacuum.c:622
#12 0x0000000000d1a5fb in ExecVacuum () at vacuum.c:449
#13 0x00000000014d17b7 in standard_ProcessUtility () at utility.c:859
#14 0x00000000014d2a28 in ProcessUtility () at utility.c:523
#15 0x00000000014bd7d1 in PortalRunUtility () at pquery.c:1158
#16 0x00000000014bd377 in PortalRunMulti () at pquery.c:1315
#17 0x00000000014bffaf in PortalRun () at pquery.c:791
#18 0x00000000014ad5d9 in exec_simple_query () at postgres.c:1274
#19 0x00000000014b3d8e in PostgresMain () at postgres.c:4679
#20 0x00000000014b53b4 in PostgresSingleUserMain () at postgres.c:4135
#21 0x0000000000ee01c8 in main () at main.c:194
